# Generated by Django 4.2.4 on 2023-08-23 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("e_retrieve_auth", "0002_department_semester_session"),
    ]

    operations = [
        migrations.CreateModel(
            name="PastQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_title", models.CharField(max_length=100)),
                ("file", models.FileField(upload_to="uploads/")),
                ("date_uploaded", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department",
                        to="e_retrieve_auth.department",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semester",
                        to="e_retrieve_auth.semester",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session",
                        to="e_retrieve_auth.session",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Past Questions",
                "db_table": "Past Question",
            },
        ),
    ]
