# Generated by Django 4.2.4 on 2023-08-23 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("e_retrieve_auth", "0003_pastquestion"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pastquestion", old_name="file", new_name="past_question",
        ),
    ]
